version: '3'

services:
  minetrack:
    image: augustinominh/minetrack
    restart: always
    volumes:
      - /opt/minevn/mc-tracker/minetrack/data:/usr/src/minetrack/data
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-replace-me}
    depends_on:
      - influxdb
    networks:
      - minevn-web

  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - minevn-web

volumes:
  influxdb-data:
  influxdb-config:
